### ISSUE TITLE
Color Picker error

### ISSUE THREAD

**Issue by edap** [kashimAstro/ofxGLSLMaterial#1]
Hi. I'm trying to use your addon in OF 0.9.3, unfortunately running the example I've the following error from the color picker class:

<img width="554" alt="screen shot 2017-01-08 at 15 24 21" src="https://cloud.githubusercontent.com/assets/161152/21750579/9e3c1a5a-d5b6-11e6-86a8-2f08dfb547d1.png">

**Comment by edap** [comment]
(the `height` and `width` error are fixed using `getWidth()` and `getHeight`)

**Comment by kashimAstro** [comment]
Hi @edap,

thanks for this,I replaced width and height with getWidth() and getHeight(),
I replaced reloadTexture() with update(), getTextureReference() with getTexture() and loadImage() with load().

thanks and good day!!

**Comment by edap** [comment]
you are fast! thank you very much, I will try later and let you know.
